spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: ms-empleados
          uri: http://localhost:9000
         # uri: http://host.docker.internal:9000
          predicates:
            - Path=/api/empleados/**
        - id: ms-empresas
          uri: http://localhost:9001
        #  uri: http://host.docker.internal:9001
          predicates:
            - Path=/api/empresas/**

server:
  port: 9111

eureka:
  client:
    serviceUrl:
      #defaultZone: "http://host.docker.internal:8761/eureka/"
      defaultZone: "http://localhost:8761/eureka/"
    registerWithEureka: true
    fetchRegistry: true
