spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: ms-empleados
          uri: http://localhost:9000
          predicates:
            - Path=/api/empleados/**
        - id: ms-user-service
          uri: http://localhost:9001
          predicates:
            - Path=/api/empresas/**

server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"
    registerWithEureka: true
    fetchRegistry: true
