
spring:
  application:
    name: ms-empresas
  datasource:
    url: jdbc:mysql://localhost:3308/empresasDB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true

server:
  port: 9000

logging:
  level:
    org:
      hibernate:
        SQL: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
